apiVersion: v1
kind: Service
metadata:
  name: backendapp
  labels:
    app: backendapp
spec:
  ports:
    # the port that this service should serve on
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32739
  selector:
    app: backendapp
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backendapp
spec:
  template:
    metadata:
      labels:
        app: backendapp
        tier: backend
    spec:

      containers:
      - name: backendapp-container
        image: backendapp:latest   
        imagePullPolicy: Never        
        ports:
        - containerPort: 80             
---