apiVersion: v1
kind: Service
metadata:
  name: frontendapp
  labels:
    app: frontendapp
spec:
  ports:
    # the port that this service should serve on
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31523
  selector:
    app: frontendapp
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontendapp
spec:
  template:
    metadata:
      labels:
        app: frontendapp
        tier: backend
    spec:
      containers:
      - name: frontendapp-container
        image: frontendapp:latest       
        imagePullPolicy: Never        
        ports:
        - containerPort: 80      
---